### ISSUE TITLE
Cannot reinstall add-on

### ISSUE THREAD

**Issue by bubbl** [jelastic-jps/lets-encrypt#10]
If you remove the add-on and then try to install it again, nothing happens, the installation notification just spins on the dashboard and no operations are performed on container.

Suspect it may be related to #8

**Comment by ihorman** [comment]
Hi Bart, the bug was checked by our  QA on latest addon version and they were not able to reproduce this, we will do some additional checks and I will give you update on this. Thank you for reporting the issue and helping us to do the addon better ;)

**Comment by ihorman** [comment]
works fine now so closing the ticket, thanks ;)
