### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by ovesco** [jelastic-jps/lets-encrypt#109]
As stated here: [https://letsencrypt.org/docs/ipv6-support/](https://letsencrypt.org/docs/ipv6-support/), let's encrypt now supports IPv6 and prefers it over IPv4. It would be great if this addon didn't absolutely require an IPv4 address to work.

For example given a balancing node which already has an IPv6 address attached, do not create an IPv4 address, otherwise do it.

**Comment by ihorman** [comment]
Hello, thank you for the valid feedback, the team is going to fix this issue shortly.

**Comment by ovesco** [comment]
Is there any news on this ?

**Comment by SlavaKatiukha** [comment]
Hello, @ovesco. 
Thanks for your patience.
Actually, the issue was fixed a couple of months ago under another task: https://github.com/jelastic-jps/lets-encrypt/commit/6ae80837c862ae4a985cd159d63eb3d85250de59.
You can try to attach IPv6 to the balancing node and install the add-on after that.
