### ISSUE TITLE
Cannot generate certificate, user with UID[1] cannot be found

### ISSUE THREAD

**Issue by vincentjanv** [jelastic-jps/lets-encrypt#2]
When trying to generate a certificate for either the env.domain of custom domain, it will fail.  The detailed error log mentions an error :'user with UID[1] cannot be found'. 

What are the exact requirements to be able to install an SSL from let's encrypt? Eg: should a public ip already be assigned, is only apache supported, can I have a loadbalancer in front...

**Comment by marcosArruda** [comment]
+1 wanting to try it out.

**Comment by sych74** [comment]
@vincentjanv, @marcosArruda: the package is almost ready, in QA stage. You can try it now. Let us know if any issues. + @ihorman

**Comment by vincentjanv** [comment]
Great, will do. Thanks for notifying us.
