### ISSUE TITLE
Can't read ssl certificate while trying to add a new subdomain

### ISSUE THREAD

**Issue by fredrabelo** [jelastic-jps/lets-encrypt#22]
I am trying to update my certificate on Jelastic, and add a new subdomain, (it is already on and working, but it will expire next week), but I get the following error:

An unknown error has occurred. Please try again later. We apologize for the inconvenience.

Does anybody know what could be the problem?
Here are the details: 

{"response":"Can't read ssl certificate: key={\"result\":0,\"body\":\"\"} cert={\"result\":0,\"body\":\"\"} chain={\"result\":0,\"body\":\"\"}","message":"Can't read ssl certificate: key={\"result\":0,\"body\":\"\"} cert={\"result\":0,\"body\":\"\"} chain={\"result\":0,\"body\":\"\"}","result":99,"error":"Can't read ssl certificate: key={\"result\":0,\"body\":\"\"} cert={\"result\":0,\"body\":\"\"} chain={\"result\":0,\"body\":\"\"}","debug":[{"result":0,"responses":[{"result":0,"errOut":"--2017-07-11 02:00:02-- https://raw.githubusercontent.com/jelastic-jps/lets-encrypt/master/scripts/install-le.sh?_r=0.8376737327458548\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.56.133\nConnecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.56.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 844 [text/plain]\nSaving to: ‘/root/install-le.sh’\n\n 0K 100% 180M=0s\n\n2017-07-11 02:00:03 (180 MB/s) - ‘/root/install-le.sh’ saved [844/844]\n\n--2017-07-11 02:00:07-- https://raw.githubusercontent.com/jelastic/jem/master/usr/lib/jelastic/modules/ssl.module\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.56.133\nConnecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.56.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 3054 (3.0K) [text/plain]\nSaving to: ‘/usr/lib/jelastic/modules/ssl.module’\n\n 0K .. 100% 33.3M=0s\n\n2017-07-11 02:00:07 (33.3 MB/s) - ‘/usr/lib/jelastic/modules/ssl.module’ saved [3054/3054]","exitStatus":0,"nodeid":105065,"out":""}]},{"result":0,"responses":[{"result":0,"errOut":"--2017-07-11 02:00:08-- https://raw.githubusercontent.com/jelastic-jps/lets-encrypt/master/scripts/generate-ssl-cert.sh?_r=0.8376737327458548\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.56.133\nConnecting to raw.githubusercontent.com

**Comment by SrMordred** [comment]
Have you solved?
Same issue here.

**Comment by ihorman** [comment]
Hello  Patric and Fred. The problem was caused by some changes on a side of certbot. Now it is fixed from the addon side as well. Please try re-install addon and that should work.
Thank you for your help!
