### ISSUE TITLE
Cannot add more domains after initial install

### ISSUE THREAD

**Issue by Intonode** [jelastic-jps/lets-encrypt#26]
It doesn't allow you to add more domain after the initial setup, I have had to un-install and start again every time I want to add another domain name!

Where in the file system does this store the certificates?

**Comment by ihorman** [comment]
After the certificates are processed by the tool they are placed to /var/lib/jelastic/SSL/.
As for adding another domain without re-installation - good idea. Added to a backlog.
Thanks!

**Comment by siruslan** [comment]
@Intonode, right you can try out this updated version https://github.com/jelastic-jps/lets-encrypt/blob/validations/manifest.jps, it provides "Configure" option. It will be merged to the master later after a proper testing.

**Comment by ihorman** [comment]
The feature was merged to master and now available in production.
