### ISSUE TITLE
Error whilst installing on fresh instance

### ISSUE THREAD

**Issue by bbredewold** [jelastic-jps/lets-encrypt#27]
I'm getting this error now:
`Can't read ssl certificate: key={"result":0,"body":""} cert={"result":0,"body":""} chain={"result":0,"body":""}`

**Comment by siruslan** [comment]
Please provide the environment name. 
+ @ihorman

**Comment by bbredewold** [comment]
I'm trying to install it on an Nginx server.
I'm hosting it with Hostnet (Netherlands) using Jelastic.

**Comment by ihorman** [comment]
@bbredewold, please check installation once again, this issue was fixed recently, the problem was related to verification type change from TLS-01 to HTTP-01, as TLS-01 is now considered in LE as insecured.   Please let us know if that works for you now. Thanks!

**Comment by ihorman** [comment]
Fixed and merged to master.
