### ISSUE TITLE
Failed authorization procedure.

### ISSUE THREAD

**Issue by aadii104** [jelastic-jps/lets-encrypt#29]
Hello there, 
I am trying to get my certificate but getting this error.
system :- debian 9 on digital ocean.
domain name:- ss1.proworktree.com
I am also able to ping the ipaddress from my system and have enabled both ipv4 and ipv6 from digital ocean.
error:- 
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: ss1.proworktree.com
   Type:   connection
   Detail: Fetching
   http://ss1.proworktree.com/.well-known/acme-challenge/hIWSTAhj-STzDdsB1rEZXA-Cdafo11xW5Bgf0CsNJxo:
   Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

**Comment by ihorman** [comment]
Hi @aadii104 , that is a github repo of Let's Encrypt addon for Jelastic Platform, we are not aware of the way it is working on Digital Ocean, but from that error log you provided I assume you have your DNS settings misconfigured in place.  The service of LE makes a callback request to a domain ss1.proworktree.com and cannot reach that challenge file.

**Comment by aadii104** [comment]
sure @ihorman ,
thanks for the help.

**Comment by ihorman** [comment]
Good luck 👍
