### ISSUE TITLE
Old version removed

### ISSUE THREAD

**Issue by Zoltan-LS** [jelastic-jps/lets-encrypt#3]
This is not working in the current state. 
I think you ditched the original version and started from scratch.

The verification process can be performed easier with web-check.
The manifest doesnt cover load balancers
Letsencrypt updates packages like mod_ssl and httpd on the env. That is not ideal.  

I modifed your original version and got it working , but I see that you are working on this a different way.

**Comment by sych74** [comment]
@Zoltan-LS, please check the latest version, it's in QA now.
