### ISSUE TITLE
Let's Encrypt Jelastic eApps plugin not working with Payara 4.1.2.174

### ISSUE THREAD

**Issue by tlarsonlgdor** [jelastic-jps/lets-encrypt#30]
Payara was added to the manifest on Jan 11th. Using the Jelastic Dashboard on eApps host, it will install as normal. However, ssl call in Firefox vers. 58 provides the typical "...connection is not secure..." response. If Payara isn't supported, when/will it be and what versions will be supported?

**Comment by ihorman** [comment]
Hi, could you please provide your environment name on eApps, I will ask support to take a look the issue closer?  thanks

**Comment by tlarsonlgdor** [comment]
Hi. Thanks. Environment name is:  http://universalvote.njs.jelastic.vps-host.net/

 

I have already put a request to support and their response wat that Payara wasn’t supported yet. Could it be the plug-in version they’re using?

**Comment by ihorman** [comment]
Hi @tlarsonlgdor, guys from support team just fixed the issue. Could you please check if everything works fine?

**Comment by tlarsonlgdor** [comment]
That did it! Thanks for the help! That saves us a lot of money and time!

**Comment by ihorman** [comment]
Thank you! )
