### ISSUE TITLE
Punycode support

### ISSUE THREAD

**Issue by ReTWi** [jelastic-jps/lets-encrypt#53]
Can you add punycode support to addon?

**Comment by dzotic9** [comment]
Hi Max, the ticket about your issue has been registered and fixed. It will be in the repository after the testing stage. Thanks in advance!

**Comment by dzotic9** [comment]
Hi Max, the fix has been merged. Please, try to install Let's Encrypt add-on once again. Let us know in case you have any other issues. Thanks!
