### ISSUE TITLE
Certbot lauch 

### ISSUE THREAD

**Issue by Zoltan-LS** [jelastic-jps/lets-encrypt#6]
This is a minor problem, but still could cause problems.
The whole install process launches a yum update on apache server . This might cause problems in some cases .  Updates should be controlled better . 
I think this should be avoided , just in case the env has some weird custom settings/modules. 

I dont think it is a bug , but something to consider.

**Comment by sych74** [comment]
@Zoltan-LS, seems like this issue is not valid anymore.
