### ISSUE TITLE
TypeError on line 818: Cannot call method "BindSSL" of undefined

### ISSUE THREAD

**Issue by Slamdunk** [jelastic-jps/lets-encrypt#65]
Hi, I'm using Jelastic on your Italian partner [Aruba](https://www.cloud.it/jelastic-cloud-paas/jelastic-cloud.aspx) (Jelastic version 5.7). Trying to activating the `Let's Encrypt Free SSL` on any load-balancer with any associated domain name, I get the following error:

```
{
  "result":99,
  "method":"evalScript",
  "action":"installScript.script",
  "error":"Error: {\"line\":818,\"name\":\"TypeError\",\"source\":\"script\",\"message\":\"Cannot call method \\\"BindSSL\\\" of undefined\"}",
  "__info":{
    [omitted]
  }
}
```
That clearly refers to the following line:
https://github.com/jelastic-jps/lets-encrypt/blob/master/scripts/ssl-manager.js#L818

The certificate correctly appears on https://crt.sh/ so it was issued, but the addon broke halfway through.

I've already sent the support request both by the Jelastic App popup and to Aruba direct support, without receiving any reply.

I know it's not up to this Github library to solve the issue, but can you perhaps help me figuring out where the problem could be so I can pinpoint the solution to the provider?

**Comment by ihorman** [comment]
Hello @Slamdunk 
Thank you for reporting the issue, we are checking the root cause. I will keep you updated.

**Comment by ihorman** [comment]
The issue is fixed, could you please try again?

**Comment by Slamdunk** [comment]
@ihorman technically now it works, but uses the FAKE LetsEncrypt root cert:

```
Certificate chain
 0 s:CN = env-[OMISSIS].it1.eur.aruba.jenv-aruba.cloud
   i:CN = Fake LE Intermediate X1
 1 s:CN = Fake LE Intermediate X1
   i:CN = Fake LE Root X1
```

Should I open a new ticket here or to Aruba partner?

**Comment by siruslan** [comment]
@Slamdunk, you need to use a custom external domain for issuing real certificates. It's easy and the description of this process is described in the article https://jelastic.com/blog/free-ssl-certificates-with-lets-encrypt/. For default environment domain based on the Aruba platform domain the addon always issues Fake certificates for avoiding issues with [limitations enforced by let's encrypt](https://letsencrypt.org/docs/rate-limits/) related to number of certificated per top domain.

**Comment by Slamdunk** [comment]
> For default environment domain based on the Aruba platform domain the addon always issues Fake certificates

Didn't know this, nor can't find it in the docs.

With custom domain works correctly, thanks for the support :+1:
