### ISSUE TITLE
Untrusted certificate

### ISSUE THREAD

**Issue by tjomamokrenko** [jelastic-jps/lets-encrypt#7]
I am using jelastic 4.9, nginx 1.10.1

https://www.ssllabs.com/ssltest/analyze.html?d=env-3564948.mircloud.host

Also in NGINX logs:

```
2016/12/18 04:05:06 [crit] 5829#0: *252 SSL_do_handshake() failed (SSL: error:14094085:SSL routines:SSL3_READ_BYTES:ccs received early) while SSL handshaking, client: 64.41.200.101, server: 0.0.0.0:443
```
![image](https://cloud.githubusercontent.com/assets/21218721/21291463/395549e6-c4e9-11e6-98ae-4faf86684e09.png)

**Comment by sych74** [comment]
Hi @tjomamokrenko, it was designed like that, please check the Readme at the main page 

`Environment Name Domain - creates a dummy (invalid) SSL certificate for your environment internal URL (env_name.{hoster_domain}) to be used in testing`

The valid certificate can be issued for Custom Domain only.

**Comment by tjomamokrenko** [comment]
@sych74 thanks! although it is unexpected. I can generate a self-signed cert without any add-ons.

**Comment by tjomamokrenko** [comment]
@sych74 oh, I got it, nevermind :+1:

**Comment by sych74** [comment]
@tjomamokrenko Ok, no prob, let me know if any other questions! Have a successful and enjoyable coding :)

**Comment by bubbl** [comment]
I don't really understand why it's creating invalid cert, if you can create a valid one using letsencrypt itself (without add-on), even for environment name?
